<?php
namespace app\controllers;

use app\helpers\Functions;
use app\helpers\UserPermission;
use app\models\Types;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\HttpException;
use yii\web\NotAcceptableHttpException;
use yii\web\NotFoundHttpException;

class BaseController extends Controller
{

    /*public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }*/
    public function beforeAction($action)
    {
        $user_type = null;
        if(!\Yii::$app->user->isGuest){
            $user_type= \Yii::$app->user->identity->type_id;
        }
        $controller_id = $this->id;
        $action_id = $action->id;
        $has_access = false;
        switch ($controller_id){
            case 'site':
                if(in_array($action_id,['login','error','index'])){
                    $has_access = true;
                }else{
                    $has_access = (bool)$user_type;
                }
                break;
            case 'operator':
                $has_access = in_array($user_type,[Types::OPERATOR,Types::ADMIN]);
                break;
            default:
                $has_access = $user_type = Types::ADMIN;

        }
        if(!$has_access){
            throw  new HttpException('403','Իրավասություն չունեք');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}