<?php
namespace app\controllers\api;

use app\helpers\Functions;
use app\helpers\UserPermission;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\HttpException;
use yii\web\NotAcceptableHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;


class ApiBaseController extends Controller
{


    public $enableCsrfValidation = false;
    public function beforeAction($action)
    {
        $headers = \Yii::$app->response->headers;

        $headers->add('Access-Control-Allow-Origin', '*');
        $headers->add('Access-Control-Allow-Methods', 'GET, POST, PATCH, PUT, DELETE, OPTIONS');
        $headers->add('Access-Control-Allow-Headers', 'Origin, Content-Type, X-Auth-Token');
        $_POST = \yii\helpers\Json::decode(file_get_contents("php://input"));

        \Yii::$app->response->format = Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}